[package]
name = "ktanesim"
version = "0.1.0"
authors = ["Jakub \"NieDżejkob\" Kądziołka <kuba@kadziolka.net>"]
edition = "2018"
publish = false

[dependencies]
ktane-utils = { path = "../ktane-utils" }
rand = "^0.6"

[[bin]]
name = "ktanesim"
path = "main.rs"
